@startuml conftopicmapper
json "<b>Conference Topic Mapper" as CFM {
    "HTTPServer": "to receive update from Server",
    "HTTPClient": "to update the IP-addresses at an Media Resource Function",
    "Database": "to maintain the Topic <-> Conference mapping"
}
@enduml