@startuml server
json "<b>Server" as S {
    "ConfFactory": "a SIP Conference Server addressed by a ConfURI",
    "SIPServer": "a SIP Server including Registrar and Redirect function",
    "HTTPClient": "to update the ConferenceURI-Topic mapping"
}
@enduml