@startuml Topic
json "**Topic** as a Media Resource Function-**MRF**" as MRF {
    "RESTServer": "to receive update from the Conference Topic Mapper",
    "MRF": "to forward the RTP packets from a Publisher to Subscribers"
}
@enduml