@startuml architecture
left to right direction


title IoT PubSub System using RTP/SIP

package Pubs{
node Publisher as Pub {
    [SIPClient] as PubSIPC #Orange 
    [RTPSender] #LightGreen 
}
}
package Network {
node Server as Server {
    [SIPServer] #Orange 
    [HTTPClient] as ServerHTTPC #LightBlue 
    [ConferenceFactory] #OrangeRed 
}

node Topic {
    [HTTPServer] as TopicHTTPS #LightBlue 
    [MRF] #LightGreen 
}

node ConfTopicMapper {
    [HTTPServer] as MapHTTP #LightBlue
    database DB
}
}


package Subs {
node Subscriber1 as Sub1 {
    [SIPClient] as SubSIPC1 #Orange 
    [HTTPclient] as SubHTTPC1 #LightBlue 
    [RTPReceiver] as RTPReceiver1#LightGreen 
}

node Subscriber2 as Sub2 {
    [SIPClient] as SubSIPC2 #Orange 
    [HTTPclient] as SubHTTPC2 #LightBlue 
    [RTPReceiver] as RTPReceiver2 #LightGreen 
}
node Subscriber3 as Sub3 {
    [SIPClient] as SubSIPC3 #Orange 
    [HTTPclient] as SubHTTPC3 #LightBlue 
    [RTPReceiver] as RTPReceiver3#LightGreen 
}
}



[PubSIPC] <-[#OrangeRed]-> [ConferenceFactory]: Publish Topic

[ServerHTTPC] <-[#Blue,dashed]-> MapHTTP: Update Topic-Conference map

[ServerHTTPC] -[#Blue,dashed]-> TopicHTTPS: Update forwarding addr

[SubHTTPC1] <-[#Blue,dashed]-> MapHTTP: Get ConfUri
[MapHTTP] <-> DB: ""
' [SubHTTPC2] <-[#Blue,dashed]-> ConfTopicMapper: Get ConfUri
' [SubHTTPC3] <-[#Blue,dashed]-> ConfTopicMapper: Get ConfUri

[PubSIPC] <-[#Orange]-> [SIPServer]: Join Conference
[SubSIPC1] <-[#Orange]-> [SIPServer]: Join Conference
' [SubSIPC2] <-[#Orange]-> [SIPServer]: ""
' [SubSIPC3] <-[#Orange]-> [SIPServer]: ""

[RTPSender] -[#Green,bold]-> [MRF]: RTP Stream
[MRF] -[#Green,bold]-> [RTPReceiver1]: ""
[MRF] -[#Green,bold]-> [RTPReceiver2]: ""
[MRF] -[#Green,bold]-> [RTPReceiver3]: ""

@enduml