@startuml publishing
    autonumber
    participant Pub [
        = Publisher
        ----
        IP: 10.5.0.2
    ]
    participant Server [
        = Server
        ----
        IP: 10.5.0.7
    ]
    participant ConfTopicMapper [
        = ConfTopicMapper
        ----
        IP: 10.5.0.8
    ]
    participant Topic [
        = Topic
        ----
        IP: 10.5.0.3
    ]
    participant Sub [
        = Subscriber
        ----
        IP: 10.5.0.4
    ]

    par Pub Registration
        Pub --> Server:  SIP REGISTER and 200 OK
    else Sub Registration 
        Sub --> Server: SIP REGISTER and 200 OK
    end

    group #LightGreen Check if Topic already exists 
        autonumber 5.1
        Pub ->> ConfTopicMapper: HTTP GET request\n <i>http://10.5.0.8:8080/api/v1/topicMode?topic=<color:blue>iotTopic</color></i>
        activate ConfTopicMapper
        activate Pub
        ConfTopicMapper ->> Pub: HTTP GET response\n<i> { ... </i>\n  <i>"ConfUri":"<color:red>iotConfUri</color>"</i>\n  <i>...}</i>
        deactivate Pub
        deactivate ConfTopicMapper

        alt Topic exists
            autonumber 5.3
            Pub ->> Server: SIP INVITE\n <i>sip:<color:red>iotConfUri</color>@10.5.0.7:5040</i>
            note right of Pub: m=text 6420 RTP/AVP 100\nc=IN IP4 10.5.0.2\na=rtpmap:100 <color:orange>t140/1000</color>\n<color:green>a=sendonly</color>
            Server ->> ConfTopicMapper: HTTP PATCH request\n<i>http://10.5.0.8:8080/api/v1/topicMode?topic=<color:blue>iotTopic</color></i>\n <i> { ... </i>\n  <i>"User":"publisher",</i>\n<i>"EntityUrl":"sip:publisher@10.5.0.2:5060",</i>\n<i>"Role":"sendonly",</i>\n  <i>...}</i>
            ConfTopicMapper ->> Server: HTTP PATCH response
            Server ->> Pub: SIP 200 OK
            note left of Server: m=text 6430 RTP/AVP 100\nc=IN IP4 10.5.0.3\n<color:blue>a=topic:iotTopic</color>\n<color:red>a=confUri:iotConfUri</color>\na=rtpmap:100 t140/1000\n<color:green>a=recvonly</color>
            
            Pub <-> Sub: continue as before
            
        else #White Topic NOT FOUND 404
            autonumber 5.3
                Pub ->> Server: SIP INVITE\n <i>sip:confFactory@10.5.0.7:5080</i>
                note right of Pub: m=text 6420 RTP/AVP 100\nc=IN IP4 10.5.0.2\n<color:blue>a=topic:iotTopic</color>\na=rtpmap:100 <color:orange>t140/1000</color>\n<color:green>a=sendonly</color>                
                Server ->> ConfTopicMapper: HTTP POST request\n <i>http://10.5.0.8:8080:/api/v1/topicMode/confInfos</i>\n<i>{...</i>\n <i>"ConfID":"123confIDxyz"</i>,\n <i>"Topic":"<color:blue>iotTopic</color></i>",\n <i>...}</i>
                activate Server
                ConfTopicMapper ->> Topic: HTTP POST\n<i>http://10.5.0.3:8060/</i>\n<i> { ... </i>\n  <i>a list of Participants</i>\n  <i>...}</i>
                activate ConfTopicMapper
                Topic ->> ConfTopicMapper: HTTP POST response
                deactivate ConfTopicMapper
                ConfTopicMapper ->> Server: HTTP POST response
                note over Server: create a Conference in Server
                Server ->> Pub: SIP 200 OK
                note left of Server: m=text 6430 RTP/AVP 100\nc=IN IP4 10.5.0.3\n<color:blue>a=topic:iotTopic</color>\n<color:red>a=confUri:iotConfUri</color>\na=rtpmap:100 t140/1000\n<color:green>a=recvonly</color>
                deactivate Server
        end
    end
    autonumber 6
    par Data publishing
        Pub ->> Topic: the same operations
    else Data subscription and distributing
        Topic ->> Sub: the same operations
    end

@enduml