@startuml unsubscsribe
    title Unsubscribe Sequence
    autonumber
    participant Pub [
        = Publisher
        ----
        IP: 10.5.0.2
    ]
    participant Server [
        = Server
        ----
        IP: 10.5.0.7
    ]
    participant ConfTopicMapper [
        = ConfTopicMapper
        ----
        IP:10.5.0.8
    ]
    participant Topic [
        = Topic
        ----
        IP:10.5.0.3
    ]
    participant Sub [
        = Subscriber
        ----
        10.5.0.4
    ]


    
    Note over Pub, Sub #WhiteSmoke: Data distribution in the process

    alt Pub un-publishing
        Pub ->> Server: SIP BYE\n<i>sip:<color:red>iotConfUri</color>@10.5.0.7:5040</i>
        Server ->> Pub: SIP ACK
        Pub ->x?: Stop RTP streaming
        Server ->> Sub: SIP BYE\n<i>sip:subscriber@10.5.0.4:5071</i>
        Sub ->> Server: SIP ACK
        Server ->> ConfTopicMapper: HTTP PATCH request\n<i>http://10.5.0.8:8080/api/v1/topicMode/confInfos/<color:blue>iotTopic</color>/users</i>
        ConfTopicMapper ->> Topic: HTTP PATCH request\n <i>http://10.5.0.3:8060/users/</i> 
        Note over Topic: Tear down a Topic instance
        Topic ->> ConfTopicMapper: HTTP PATCH response
        ConfTopicMapper ->> Server: HTTP PATCH response 
    else Sub unsubscribing
        Sub ->> Server: SIP BYE\n<i>sip:<color:red>iotConfUri</color>@10.5.0.7:5040</i>
        Server ->> Sub: SIP ACK
        
        Note over Sub: Stop receiving RTP Stream
        
        
        Server ->> Server: Check if one or more Subs in a Topic
        alt Topic has no Sub
            Server ->> Pub: SIP BYE\n<i>sip:publisher@10.5.0.2:5060</i>
            Pub ->> Server: SIP ACK
            Server ->> ConfTopicMapper: HTTP PATCH request\n<i>http://10.5.0.8:8080/api/v1/topicMode/confInfos/<color:blue>iotTopic</color>/users</i>
            ConfTopicMapper ->> Topic: HTTP PATCH
            ConfTopicMapper ->> Topic: HTTP PATCH request\n <i>http://10.5.0.3:8060/users/</i> 
            Note over Topic: Tear down a Topic instance
            Pub ->x?: Stop RTP streaming
        else Topic has one or more Subs
            Pub ->> Topic: Continue streaming for other Subs
        end
    end
@enduml